### PR TITLE
Feat/setup tests

### PR DESCRIPTION
**Pull request by Supakrit65**
# Pull Request: Comprehensive Test Suite Update for SOTA API

## Overview

This pull request introduces a significant update to our testing framework for the SOTA API. It aligns our `tests/` files with the comprehensive test plan outlined in the README, ensuring thorough and systematic validation of all API functionalities.

### Key Highlights

- **Test Case:** Integrated unittest test cases for the SOTA API as per the detailed test plan. This includes tests for authentication, sports API, medal API, and audience information update functionalities.
- **Test Plan Documentation:** Updated the README file to include a detailed test plan. This plan provides a clear structure and guide for current and future test scenarios.
- **Testing Tools Used:** Python unittest and Mongomock have been employed to simulate and test various API routes and scenarios effectively.

### Overview of Changes

The following is a detailed overview of each `tests/test_*.py` file and the specific functionalities they target:

1. **`test_authentication.py`**:
   - This file contains tests related to user authentication and token validation.
   - It ensures that API endpoints behave correctly under various authentication scenarios, including access with valid/invalid tokens and checking for user permissions.

2. **`test_get_medal_route.py`**:
   - Focuses on testing the retrieval of medal information.
   - It verifies correct responses for both existing and non-existing parameters, ensuring the API accurately handles requests related to medal data.

3. **`test_sport_route.py`**:
   - Contains tests for the functionality of the SportRouter.
   - These tests cover scenarios for retrieving sport information based on sport ID, including both valid and invalid ID requests.

4. **`test_update_audient_info.py`**:
   - Dedicated to testing the updating of audience information.
   - It includes various scenarios, ensuring the API correctly handles valid and invalid request bodies for audience data updates.

5. **`test_update_medal_route.py`**:
   - Tests the `/medals/update_medal` endpoint specifically.
   - Ensures the correct handling of medal update requests under different scenarios, including correct and incorrect data submissions.

### Impact

- **Enhanced Reliability:** These tests ensure that all aspects of the SOTA API function as expected under various scenarios.
- **Streamlined Testing Process:** Clear documentation in the README facilitates easy understanding and execution of tests.
- **Future Development:** Provides a robust foundation for future feature additions and modifications to be tested thoroughly.

### Testing Execution

Tests can be executed as described in the updated README file. This includes both individual test executions and running the entire suite.

### CODE REVIEW

**Review by RyukungG — DISMISSED** [review]

**Comment by GToidZ** [comment]
@Supakrit65 Is there a specific reason why `httpx` is a requirement?

**Comment by Supakrit65** [comment]
> @Supakrit65 Is there a specific reason why `httpx` is a requirement?

image

**Review by GToidZ — DISMISSED** [review]
LGTM it is then. Seems like a really unpopular choice by FastAPI to not properly mention `extras` dependencies in their docs.

**Review by Halcyon905 — DISMISSED** [review]

**Review by Hamiz5401 — DISMISSED** [review]

**Review by RyukungG — DISMISSED** [review]

**Review by Hamiz5401 — APPROVED** [review]

**Review by Halcyon905 — APPROVED** [review]
seems good to me

**Review by RyukungG — APPROVED** [review]

**Pull request merged**
