### PR TITLE
Update HTTP status code responses for validation errors

### PR DESCRIPTION
**Pull request by Supakrit65**
## Overview
This pull request updates the HTTP status code returned for validation errors from `422 Unprocessable Entity` to `400 Bad Request`. The changes affect two endpoints:

- `/medals/update_medal`
- `/audient/update_audient_info`

## Changes
- The `update_medal` endpoint now returns a `400 Bad Request` status code when there are missing fields or invalid field values.
- Similarly, the `update_audient_info` endpoint has been updated to return a `400 Bad Request` status code under the same circumstances.

## Rationale
The HTTP 422 status code is meant for situations where the server understands the content type of the request entity, and the syntax of the request entity is correct, but it was unable to process the contained instructions. However, for general validation errors such as missing fields or invalid field values, a `400 Bad Request` is more appropriate. This change aligns our API with the standard usage of HTTP status codes.

Please review the changes and provide your feedback.

Regards,
Jack Hanma

### CODE REVIEW

**Review by RyukungG — APPROVED** [review]

**Review by Hamiz5401 — APPROVED** [review]

**Review by Halcyon905 — APPROVED** [review]

**Review by GToidZ — APPROVED** [review]
Great! The status code is now sensible rather than it being `422`. It is now a good idea to merge.

**Pull request merged**
