### PR TITLE
feat: Implement GET `/medal/s/:sport_id` endpoint with `sub_sports`

### PR DESCRIPTION
**Pull request by Supakrit65**
## This PR adds to and modifies the system by:

- Add working implementation for GET /medal/s/:sport_id endpoint
- I actually tested it on the mock data, so it should be fine. **Trust me bro!**

### Here is what mock data looks like
```
[{
  "_id": {
    "$oid": "65390087f4fddded9fea2357"
  },
  "country_code": "US",
  "country_name": "United States of America",
  "sports": [
    {
      "sport_id": 1,
      "type_id": 1,
      "gold": 10,
      "silver": 10,
      "bronze": 0
    },
    {
      "sport_id": 1,
      "type_id": 2,
      "gold": 20,
      "silver": 10,
      "bronze": 10
    },
    {
      "sport_id": 2,
      "type_id": 3,
      "gold": 10,
      "silver": 0,
      "bronze": 0
    }
  ]
},
{
  "_id": {
    "$oid": "65390087f4fddded9fea2358"
  },
  "country_code": "GB",
  "country_name": "United Kingdom",
  "sports": [
    {
      "sport_id": 6,
      "type_id": 1,
      "gold": 0,
      "silver": 100,
      "bronze": 100
    },
    {
      "sport_id": 15,
      "type_id": 4,
      "gold": 0,
      "silver": 0,
      "bronze": 100
    }
  ]
},
{
  "_id": {
    "$oid": "65390087f4fddded9fea2359"
  },
  "country_code": "CN",
  "country_name": "China",
  "sports": [
    {
      "sport_id": 1,
      "type_id": 1,
      "gold": 1000,
      "silver": 0,
      "bronze": 1000
    },
    {
      "sport_id": 2,
      "type_id": 2,
      "gold": 1000,
      "silver": 0,
      "bronze": 0
    },
    {
      "sport_id": 2,
      "type_id": 3,
      "gold": 1000,
      "silver": 1000,
      "bronze": 3000
    }
  ]
}]
```
### Here is examples for the query result
- medal/s/1
```
{
	"sport_name": "Archery",
	"gold": 1030,
	"silver": 20,
	"bronze": 1010,
	"individual_countries": [
		{
			"country_code": "US",
			"country_name": "United States of America",
			"gold": 30,
			"silver": 20,
			"bronze": 10,
			"sub_sports": [
				{
					"sub_id": 1,
					"sub_name": "Individual Men's",
					"gold": 10,
					"silver": 10,
					"bronze": 0
				},
				{
					"sub_id": 2,
					"sub_name": "Individual Women's",
					"gold": 20,
					"silver": 10,
					"bronze": 10
				}
			]
		},
		{
			"country_code": "CN",
			"country_name": "China",
			"gold": 1000,
			"silver": 0,
			"bronze": 1000,
			"sub_sports": [
				{
					"sub_id": 1,
					"sub_name": "Individual Men's",
					"gold": 1000,
					"silver": 0,
					"bronze": 1000
				}
			]
		}
	],
	"sport": 1
}
```

### CODE REVIEW

**Comment by Supakrit65** [comment]
Alt Text

**Review by Hamiz5401 — DISMISSED** [review]

**Review by RyukungG — CHANGES_REQUESTED** [review]
Can you add more about SubSport

**Review by RyukungG — DISMISSED** [review]
Ok Look good

**Comment by Supakrit65** [comment]
Alt Text

**Review by Hamiz5401 — DISMISSED** [review]

**Review by GToidZ — CHANGES_REQUESTED** [review]
This branch also has the same behavior as #12. Needs fixing before merge 🙏

**Review by GToidZ — APPROVED** [review]
Looking good now! It works and has correct format as discussed in #11.

Please also add "closes #11" to your commit message when merging.

**Review by RyukungG — APPROVED** [review]
Look ok

**Review by Halcyon905 — APPROVED** [review]
very nice

**Pull request merged**
