### PR TITLE
feat: Implement GET `/medals` and POST `/medals/update_medal` endpoint

### PR DESCRIPTION
**Pull request by Supakrit65**
# This PR adds to and modifies the system by:

- Implement functionality for the `GET /medals` endpoint.
- Implement functionality for the `POST /medals/update_medal` endpoint.

### Here is what mock data looks like
```
[{
  "_id": {
    "$oid": "65390087f4fddded9fea2357"
  },
  "country_code": "US",
  "country_name": "United States of America",
  "sports": [
    {
      "sport_id": 1,
      "type_id": 1,
      "gold": 10,
      "silver": 10,
      "bronze": 0
    },
    {
      "sport_id": 1,
      "type_id": 2,
      "gold": 20,
      "silver": 10,
      "bronze": 10
    },
    {
      "sport_id": 2,
      "type_id": 3,
      "gold": 10,
      "silver": 0,
      "bronze": 0
    }
  ]
},
{
  "_id": {
    "$oid": "65390087f4fddded9fea2358"
  },
  "country_code": "GB",
  "country_name": "United Kingdom",
  "sports": [
    {
      "sport_id": 6,
      "type_id": 1,
      "gold": 0,
      "silver": 100,
      "bronze": 100
    },
    {
      "sport_id": 15,
      "type_id": 4,
      "gold": 0,
      "silver": 0,
      "bronze": 100
    }
  ]
},
{
  "_id": {
    "$oid": "65390087f4fddded9fea2359"
  },
  "country_code": "CN",
  "country_name": "China",
  "sports": [
    {
      "sport_id": 1,
      "type_id": 1,
      "gold": 1000,
      "silver": 0,
      "bronze": 1000
    },
    {
      "sport_id": 2,
      "type_id": 2,
      "gold": 1000,
      "silver": 0,
      "bronze": 0
    },
    {
      "sport_id": 2,
      "type_id": 3,
      "gold": 1000,
      "silver": 1000,
      "bronze": 3000
    }
  ]
}]
```
### Here is examples for the query result
- /medals
```
{
	"US": {
		"gold": 40,
		"silver": 20,
		"bronze": 10
	},
	"GB": {
		"gold": 0,
		"silver": 100,
		"bronze": 200
	},
	"CN": {
		"gold": 3000,
		"silver": 1000,
		"bronze": 4000
	}
}
```
### For the `POST /medals/update_medal` endpoint, validations have been added to check:
- If the participating countries are valid for the specified sport and sport type.
- Basic integer, str value constraints.

### The `update_medal` function performs the following steps:

1. Iterates over each participant in the provided data.
2. For each participant:
    a. Extracts the `country_code` and constructs a `sport_data` dictionary that contains details like sport_id, type_id, and medal counts (gold, silver, bronze).
    b. Attempts to update an existing document in the `medal_collection` based on matching criteria: country_code, sport_id, and type_id. If matched, it updates the medal counts.
    c. If the previous step did not find a match and therefore did not update:
        i. Tries to add the `sport_data` to the existing country's document in the collection.
        ii. If the country does not exist in the collection at all, fetches the country's name using the `pycountry` library and then inserts a new document with the country_code, country_name, and sport_data.
3. Once all participants are processed, it returns a success message along with the provided data.

### CODE REVIEW

**Review by GToidZ — DISMISSED** [review]
It works! Nice job

**Review by MarojT — APPROVED** [review]
nice

**Review by Hamiz5401 — APPROVED** [review]
From what I read the changes I should be fine ._.)b

**Review by RyukungG — APPROVED** [review]
Good

**Pull request merged**
