### PR TITLE
feat: Implement `GET /medal/c/c:country_code` endpoint

### PR DESCRIPTION
**Pull request by Supakrit65**
## This PR adds to and modifies the system by:

- Add working implementation for GET /medal/c/c:country_code endpoint
- I actually tested it on the mock data, so it should be fine. **Trust me bro!**
Screenshot 2566-10-28 at 13 13 06
Screenshot 2566-10-28 at 13 13 35

### CODE REVIEW

**Review by Halcyon905 — APPROVED** [review]

**Review by Hamiz5401 — APPROVED** [review]
Good job kub

**Comment by Supakrit65** [comment]
Alt Text

**Review by MarojT — APPROVED** [review]
I trust you BRO!

**Pull request merged**
